spring.application.name=BMS

spring.datasource.url=jdbc:mysql://trolley.proxy.rlwy.net:12312/railway?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=gIuZaqcZFqKRfuVRLtXLkrJYYPnIrJcB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}